version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: contacts_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: python08
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000